.PHONY: all
all: generate-api generate-controller generate-event generate-library-go generate-library-js

.PHONY: generate-api
generate-api:
	dp generate-project  --create-repository n --name "dp-hello-world-api" --description "Example api project generated by dp-cli" --rt-version 1.23.4 --port 8123 --project-location . --type api --team-slugs dissemination

.PHONY: generate-controller
generate-controller:
	dp generate-project  --create-repository n --name "dp-hello-world-controller" --description "Example controller project generated by dp-cli" --rt-version 1.23.4 --port 8124 --project-location . --type controller --team-slugs dissemination

.PHONY: generate-event
generate-event:
	dp generate-project  --create-repository n --name "dp-hello-world-event" --description "Example event driven app project generated by dp-cli" --rt-version 1.23.4 --port 8123 --project-location . --type event-driven --team-slugs dissemination

.PHONY: generate-library-go
generate-library-go:
	dp generate-project  --create-repository n --name "dp-hello-world-library-go" --description "Example go library project generated by dp-cli" --rt-version 1.23.4 --project-location . --project-language go --type library --team-slugs dissemination

.PHONY: generate-library-js
generate-library-js:
	dp generate-project  --create-repository n --name "dp-hello-world-library-js" --description "Example javascript library project generated by dp-cli" --rt-version 20.3.1 --project-location . --project-language javascript --type library --team-slugs dissemination
