---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 20.3.1

inputs:
  - name: dp-hello-world-library-js

outputs:
  - name: build

run:
  path: dp-hello-world-library-js/ci/scripts/build.sh
