// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handlers

import (
	"github.com/ONSdigital/dis-design-system-go/model"
	"io"
	"sync"
)

// Ensure, that ClientErrorMock does implement ClientError.
// If this is not the case, regenerate this file with moq.
var _ ClientError = &ClientErrorMock{}

// ClientErrorMock is a mock implementation of ClientError.
//
//	func TestSomethingThatUsesClientError(t *testing.T) {
//
//		// make and configure a mocked ClientError
//		mockedClientError := &ClientErrorMock{
//			CodeFunc: func() int {
//				panic("mock out the Code method")
//			},
//			ErrorFunc: func() string {
//				panic("mock out the Error method")
//			},
//		}
//
//		// use mockedClientError in code that requires ClientError
//		// and then make assertions.
//
//	}
type ClientErrorMock struct {
	// CodeFunc mocks the Code method.
	CodeFunc func() int

	// ErrorFunc mocks the Error method.
	ErrorFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Code holds details about calls to the Code method.
		Code []struct {
		}
		// Error holds details about calls to the Error method.
		Error []struct {
		}
	}
	lockCode  sync.RWMutex
	lockError sync.RWMutex
}

// Code calls CodeFunc.
func (mock *ClientErrorMock) Code() int {
	if mock.CodeFunc == nil {
		panic("ClientErrorMock.CodeFunc: method is nil but ClientError.Code was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCode.Lock()
	mock.calls.Code = append(mock.calls.Code, callInfo)
	mock.lockCode.Unlock()
	return mock.CodeFunc()
}

// CodeCalls gets all the calls that were made to Code.
// Check the length with:
//
//	len(mockedClientError.CodeCalls())
func (mock *ClientErrorMock) CodeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCode.RLock()
	calls = mock.calls.Code
	mock.lockCode.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *ClientErrorMock) Error() string {
	if mock.ErrorFunc == nil {
		panic("ClientErrorMock.ErrorFunc: method is nil but ClientError.Error was just called")
	}
	callInfo := struct {
	}{}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	return mock.ErrorFunc()
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedClientError.ErrorCalls())
func (mock *ClientErrorMock) ErrorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// Ensure, that RenderClientMock does implement RenderClient.
// If this is not the case, regenerate this file with moq.
var _ RenderClient = &RenderClientMock{}

// RenderClientMock is a mock implementation of RenderClient.
//
//	func TestSomethingThatUsesRenderClient(t *testing.T) {
//
//		// make and configure a mocked RenderClient
//		mockedRenderClient := &RenderClientMock{
//			BuildPageFunc: func(w io.Writer, pageModel interface{}, templateName string)  {
//				panic("mock out the BuildPage method")
//			},
//			NewBasePageModelFunc: func() model.Page {
//				panic("mock out the NewBasePageModel method")
//			},
//		}
//
//		// use mockedRenderClient in code that requires RenderClient
//		// and then make assertions.
//
//	}
type RenderClientMock struct {
	// BuildPageFunc mocks the BuildPage method.
	BuildPageFunc func(w io.Writer, pageModel interface{}, templateName string)

	// NewBasePageModelFunc mocks the NewBasePageModel method.
	NewBasePageModelFunc func() model.Page

	// calls tracks calls to the methods.
	calls struct {
		// BuildPage holds details about calls to the BuildPage method.
		BuildPage []struct {
			// W is the w argument value.
			W io.Writer
			// PageModel is the pageModel argument value.
			PageModel interface{}
			// TemplateName is the templateName argument value.
			TemplateName string
		}
		// NewBasePageModel holds details about calls to the NewBasePageModel method.
		NewBasePageModel []struct {
		}
	}
	lockBuildPage        sync.RWMutex
	lockNewBasePageModel sync.RWMutex
}

// BuildPage calls BuildPageFunc.
func (mock *RenderClientMock) BuildPage(w io.Writer, pageModel interface{}, templateName string) {
	if mock.BuildPageFunc == nil {
		panic("RenderClientMock.BuildPageFunc: method is nil but RenderClient.BuildPage was just called")
	}
	callInfo := struct {
		W            io.Writer
		PageModel    interface{}
		TemplateName string
	}{
		W:            w,
		PageModel:    pageModel,
		TemplateName: templateName,
	}
	mock.lockBuildPage.Lock()
	mock.calls.BuildPage = append(mock.calls.BuildPage, callInfo)
	mock.lockBuildPage.Unlock()
	mock.BuildPageFunc(w, pageModel, templateName)
}

// BuildPageCalls gets all the calls that were made to BuildPage.
// Check the length with:
//
//	len(mockedRenderClient.BuildPageCalls())
func (mock *RenderClientMock) BuildPageCalls() []struct {
	W            io.Writer
	PageModel    interface{}
	TemplateName string
} {
	var calls []struct {
		W            io.Writer
		PageModel    interface{}
		TemplateName string
	}
	mock.lockBuildPage.RLock()
	calls = mock.calls.BuildPage
	mock.lockBuildPage.RUnlock()
	return calls
}

// NewBasePageModel calls NewBasePageModelFunc.
func (mock *RenderClientMock) NewBasePageModel() model.Page {
	if mock.NewBasePageModelFunc == nil {
		panic("RenderClientMock.NewBasePageModelFunc: method is nil but RenderClient.NewBasePageModel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNewBasePageModel.Lock()
	mock.calls.NewBasePageModel = append(mock.calls.NewBasePageModel, callInfo)
	mock.lockNewBasePageModel.Unlock()
	return mock.NewBasePageModelFunc()
}

// NewBasePageModelCalls gets all the calls that were made to NewBasePageModel.
// Check the length with:
//
//	len(mockedRenderClient.NewBasePageModelCalls())
func (mock *RenderClientMock) NewBasePageModelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNewBasePageModel.RLock()
	calls = mock.calls.NewBasePageModel
	mock.lockNewBasePageModel.RUnlock()
	return calls
}
