---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.1

inputs:
  - name: dp-hello-world-controller

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-hello-world-controller/ci/scripts/build.sh
