---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.16.7

inputs:
  - name: dp-hello-world-event

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-hello-world-event/ci/scripts/build.sh
