---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dp-hello-world-library

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-hello-world-library/ci/scripts/build.sh
